/*
 * Acunetix12 client api
 *
 * Acunetix12 client api [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LoginReq {
    #[serde(rename = "email")]
    pub email: String,
    /// sha256(password)
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "remember_me", skip_serializing_if = "Option::is_none")]
    pub remember_me: Option<bool>,
    #[serde(rename = "logout_previous", skip_serializing_if = "Option::is_none")]
    pub logout_previous: Option<bool>,
}

impl LoginReq {
    pub fn new(email: String, password: String) -> LoginReq {
        LoginReq {
            email,
            password,
            remember_me: None,
            logout_previous: None,
        }
    }
}


