/*
 * Acunetix12 client api
 *
 * Acunetix12 client api [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Pagination {
    #[serde(rename = "previous_cursor", skip_serializing_if = "Option::is_none")]
    pub previous_cursor: Option<i64>,
    #[serde(rename = "next_cursor", skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<i64>,
}

impl Pagination {
    pub fn new() -> Pagination {
        Pagination {
            previous_cursor: None,
            next_cursor: None,
        }
    }
}


