/*
 * Acunetix12 client api
 *
 * Acunetix12 client api [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ScanStatServerityCounts {
    #[serde(rename = "high", skip_serializing_if = "Option::is_none")]
    pub high: Option<i64>,
    #[serde(rename = "medium", skip_serializing_if = "Option::is_none")]
    pub medium: Option<i64>,
    #[serde(rename = "low", skip_serializing_if = "Option::is_none")]
    pub low: Option<i64>,
}

impl ScanStatServerityCounts {
    pub fn new() -> ScanStatServerityCounts {
        ScanStatServerityCounts {
            high: None,
            medium: None,
            low: None,
        }
    }
}


