/*
 * AWVS12 client api
 *
 * Awvs12 client api [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ScanAppWvsMainStatus {
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<i64>,
    #[serde(rename = "avg_response_time", skip_serializing_if = "Option::is_none")]
    pub avg_response_time: Option<i64>,
    #[serde(rename = "max_response_time", skip_serializing_if = "Option::is_none")]
    pub max_response_time: Option<i64>,
    #[serde(rename = "request_count", skip_serializing_if = "Option::is_none")]
    pub request_count: Option<i64>,
}

impl ScanAppWvsMainStatus {
    pub fn new() -> ScanAppWvsMainStatus {
        ScanAppWvsMainStatus {
            location: None,
            avg_response_time: None,
            max_response_time: None,
            request_count: None,
        }
    }
}


