/*
 * AWVS12 client api
 *
 * Awvs12 client api [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TargetResp {
    /// url
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "type")]
    pub _type: String,
    #[serde(rename = "criticality")]
    pub criticality: i64,
    #[serde(rename = "target_id")]
    pub target_id: String,
}

impl TargetResp {
    pub fn new(address: String, _type: String, criticality: i64, target_id: String) -> TargetResp {
        TargetResp {
            address,
            description: None,
            _type,
            criticality,
            target_id,
        }
    }
}


