/*
 * Acunetix12 client api
 *
 * Acunetix12 client api [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://openapi-generator.tech
 */

/// TargetConfigAuthentication : http Authentication(Basic, Digest, NTLM and Kerberos (Windows only)



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TargetConfigAuthentication {
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
}

impl TargetConfigAuthentication {
    /// http Authentication(Basic, Digest, NTLM and Kerberos (Windows only)
    pub fn new() -> TargetConfigAuthentication {
        TargetConfigAuthentication {
            enabled: None,
            username: None,
            password: None,
        }
    }
}


