/*
 * Acunetix12 client api
 *
 * Acunetix12 client api [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Info {
    #[serde(rename = "acumonitor", skip_serializing_if = "Option::is_none")]
    pub acumonitor: Option<bool>,
    #[serde(rename = "build_number", skip_serializing_if = "Option::is_none")]
    pub build_number: Option<String>,
    #[serde(rename = "license", skip_serializing_if = "Option::is_none")]
    pub license: Option<Box<crate::models::License>>,
    #[serde(rename = "license_extra", skip_serializing_if = "Option::is_none")]
    pub license_extra: Option<Box<crate::models::LicenseExtra>>,
    #[serde(rename = "major_version", skip_serializing_if = "Option::is_none")]
    pub major_version: Option<String>,
    #[serde(rename = "minor_version", skip_serializing_if = "Option::is_none")]
    pub minor_version: Option<String>,
    #[serde(rename = "update_info", skip_serializing_if = "Option::is_none")]
    pub update_info: Option<Box<crate::models::UpdateInfo>>,
}

impl Info {
    pub fn new() -> Info {
        Info {
            acumonitor: None,
            build_number: None,
            license: None,
            license_extra: None,
            major_version: None,
            minor_version: None,
            update_info: None,
        }
    }
}


