/*
 * Acunetix12 client api
 *
 * Acunetix12 client api [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ScanAppVuln {
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "vuln_id", skip_serializing_if = "Option::is_none")]
    pub vuln_id: Option<String>,
    #[serde(rename = "serverity", skip_serializing_if = "Option::is_none")]
    pub serverity: Option<i64>,
    #[serde(rename = "target_info", skip_serializing_if = "Option::is_none")]
    pub target_info: Option<Box<crate::models::ScanAppTargetInfo>>,
}

impl ScanAppVuln {
    pub fn new() -> ScanAppVuln {
        ScanAppVuln {
            time: None,
            name: None,
            vuln_id: None,
            serverity: None,
            target_info: None,
        }
    }
}


