/*
 * Acunetix12 client api
 *
 * Acunetix12 client api [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Scans {
    #[serde(rename = "scans", skip_serializing_if = "Option::is_none")]
    pub scans: Option<Vec<crate::models::ScansItem>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::Pagination>>,
}

impl Scans {
    pub fn new() -> Scans {
        Scans {
            scans: None,
            pagination: None,
        }
    }
}


